#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidZebraPrint.Resource", IsApplication=true)]

namespace AndroidZebraPrint
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::AndroidZebraPrint.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::AndroidZebraPrint.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int quantity_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int dark_gray = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dakota_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int list_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int list_selector_pressed = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int About = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int FindPrinters = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int ListItemRowText = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int LoadDataFile = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int LoadFile = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int PrintButton = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int PrintQuantity = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int Quit = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int RowInfo = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int aboutAppname = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int aboutLogo = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int aboutText = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int aboutVersion = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int buttonOK = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int fileListView = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int locationInfoText = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int locationsView = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int printerListView = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int selectedPrinterTxt = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int spinnerQty = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutBox = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FindFiles = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindPrinters = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoadData = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LocationInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PrintQuantity = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int popup_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int About = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int AboutBox = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int AboutBoxText = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int AppName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int Discovered = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Find = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int FindFiles = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int FindPrinters = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int LoadDataFile = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int LoadLocations = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int NoPrinter = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int Print = 2130968581;
			
			// aapt resource value: 0x7f040012
			public const int PrintQuantity = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int Quantity_prompt = 2130968597;
			
			// aapt resource value: 0x7f040004
			public const int Quit = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int QuitApplication = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int QuitPrompt = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int RowInfo = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int SearchPrinters = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int Version = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
